### ISSUE TITLE
differences from old libraries

### ISSUE THREAD

**Issue by AleBalzan** [adafruit/Adafruit_Python_TCS34725#1]
- Platform/operating system Raspberry Pi with Raspbian 

Hi, all work fine, but I found differences from output number of new "get_raw_data" and old version of these (01/2015).
You change the type of variable from array to a single variable for channel. 
This may have influenced the the output of raw data?
What the differences from "readU16Rev" in old version and readU16LE in the newest?

**Comment by brennen** [comment]
Closing this issue, as we're deprecating this library in favor of [Adafruit_CircuitPython_TCS34725](https://github.com/adafruit/Adafruit_CircuitPython_TCS34725/).  I'm afraid I don't have a useful answer for the question posed here.
